<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Publish</name>
   <tag></tag>
   <elementGuidId>073be2cc-6494-400d-a875-4d1b58505bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/div/div/div/div/div[2]/div/div/div/div[4]/div/div/form/div[4]/label/label[2]/span[1]/span[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Check box to associate form with a workflow' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Check box to associate form with a workflow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4966cbeb-76c1-406d-bf29-c15e24c9938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss8</value>
      <webElementGuid>d27efc5f-614f-4d30-b652-c6ce2ba5aba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Check box to associate form with a workflow</value>
      <webElementGuid>6d889483-3d01-40aa-8bc7-0557f8fc6001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>804ca43a-f49f-4ca5-b5a0-c4f21b121109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e2d3a8e-e128-44ec-8ae2-657110f82f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main&quot;]/div/div/div/div/div[2]/div/div/div/div[4]/div/div/form/div[4]/label/label[2]/span[1]/span[1]/input</value>
      <webElementGuid>26ba9682-024f-4e6b-b15a-7a11e0d50b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Check box to associate form with a workflow']</value>
      <webElementGuid>bf4f3a15-2d2c-466d-b2f6-2a31a5a972cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div/div[4]/div/div/form/div[4]/label/label[2]/span/span/input</value>
      <webElementGuid>98c3e435-c15e-4bc1-8283-9564c08bd8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>92094615-a56b-425c-9294-89047e3dec69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Check box to associate form with a workflow' and @type = 'checkbox']</value>
      <webElementGuid>9e6e6697-82c8-4156-8954-3c81469aa0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
