<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download Form</name>
   <tag></tag>
   <elementGuidId>38458684-42bc-465f-9434-bece10e6f262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcf637de-4e68-47d0-9294-f6567a10cc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary pull-right btn-left </value>
      <webElementGuid>6c0e2edd-4327-435c-a68b-0ba78805c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Download Form </value>
      <webElementGuid>9bf0ea4b-f0f2-4f1e-99e0-5935f8de13ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;flex-container&quot;]/div[@class=&quot;flex-item-right&quot;]/button[@class=&quot;btn btn-outline-primary pull-right btn-left&quot;]</value>
      <webElementGuid>2582dd9d-aa8c-48c9-8955-8371a474dcad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[2]/button[2]</value>
      <webElementGuid>9d6f2d47-87da-4a1e-90ca-931a66a545db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[3]/preceding::button[3]</value>
      <webElementGuid>fde6cfa1-5026-4e33-b368-597d433c16d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/preceding::button[3]</value>
      <webElementGuid>91408eef-6e0f-4b70-a497-8fa80196939e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Form']/parent::*</value>
      <webElementGuid>9573ea3a-b4a8-4d6b-88f9-f85aa4857485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b487f512-546d-4ce4-bea7-265f16bd423e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Download Form ' or . = ' Download Form ')]</value>
      <webElementGuid>dd45c206-7cd0-4387-bb3f-85e4e984f6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
