<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Form Workflow Association Saved</name>
   <tag></tag>
   <elementGuidId>d13825a8-f2e8-41f8-8ee1-f35bcd05d6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kogblmcko&quot;]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;0u6vdlyxp&quot;]/div[1][count(. | //*[@role = 'alert' and (text() = 'Form Workflow Association Saved.' or . = 'Form Workflow Association Saved.')]) = count(//*[@role = 'alert' and (text() = 'Form Workflow Association Saved.' or . = 'Form Workflow Association Saved.')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc40a7d5-decf-4a37-b2a4-d002c7d361a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>a8bf3065-256a-4d2b-9cd7-9e4661411064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast-body</value>
      <webElementGuid>a8d75b11-2271-4d09-a719-dd3293e626dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form Workflow Association Saved.</value>
      <webElementGuid>8f7e12b6-d720-4dc7-b843-46de7b41d207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;0u6vdlyxp&quot;]/div[1]</value>
      <webElementGuid>1c55e3f5-7828-4737-bbfd-e952dbbedf26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4ocpbj34f']/div</value>
      <webElementGuid>40990b68-ac02-467d-84a0-4faefa56f12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[1]/following::div[10]</value>
      <webElementGuid>b2983633-b34c-431b-abdc-fe88c2562d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[10]</value>
      <webElementGuid>3b9fb09a-3b64-433a-a78c-3f4a232a8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[2]/preceding::div[2]</value>
      <webElementGuid>ed01cf47-6bd1-4b32-b67f-fadcf830fd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form Workflow Association Saved.']/parent::*</value>
      <webElementGuid>554209d9-34fd-438f-9ccb-63b0332691cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>6209aca4-d133-4758-a759-6e646ce59956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Form Workflow Association Saved.' or . = 'Form Workflow Association Saved.')]</value>
      <webElementGuid>cce6601f-3339-4013-948a-24cd2115f125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
