<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Form Saved</name>
   <tag></tag>
   <elementGuidId>e7beb0b5-229c-49fb-95dd-cd5a650022ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tcsg7qdmv']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Form Saved.' or . = 'Form Saved.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df17c37e-c8fd-4016-a197-52dae2c9ffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b6d77e9d-5c1d-4a28-86ed-6f7cf938b1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast-body</value>
      <webElementGuid>817e80c2-528d-4f67-becd-03d0c51e4609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form Saved.</value>
      <webElementGuid>e9a37665-9146-4a4f-8c12-6be21ad9de08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcsg7qdmv&quot;)/div[@class=&quot;Toastify__toast-body&quot;]</value>
      <webElementGuid>94a622cd-7b26-453c-95ef-5855cdab8183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tcsg7qdmv']/div</value>
      <webElementGuid>51986f37-0626-4584-8c78-f792ea09f6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[1]/following::div[10]</value>
      <webElementGuid>0fc2eed1-e3ef-4fbd-872d-9085d01cf178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[10]</value>
      <webElementGuid>c1a56db7-bb3e-4c3e-bc85-914591f267b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design Form'])[1]/preceding::div[2]</value>
      <webElementGuid>413c1cfd-080f-4994-ae53-32fff34c90fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate this form with a workflow?'])[1]/preceding::div[4]</value>
      <webElementGuid>35d2eab9-57f2-4685-8bb7-4b1849cb70eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form Saved.']/parent::*</value>
      <webElementGuid>3dc6391b-638c-473a-acf1-3d341e74b2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>55b293ba-360b-4b47-bae3-19989755d663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Form Saved.' or . = 'Form Saved.')]</value>
      <webElementGuid>8d0d67fd-af7e-431a-ba4c-720d6d18782a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
