<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Download Form_fa fa-download fa-lg</name>
   <tag></tag>
   <elementGuidId>be4cb307-1875-45bd-98e1-0c185b2cd934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[2]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-download.fa-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>96d966ed-ccc3-45a2-99ee-2f332bce5b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-download fa-lg</value>
      <webElementGuid>d54a3500-e385-487c-be2b-0a4c43a70250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cd3e810-ac0b-4c89-b906-d3882de71e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;flex-container&quot;]/div[@class=&quot;flex-item-right&quot;]/button[@class=&quot;btn btn-outline-primary pull-right btn-left&quot;]/i[@class=&quot;fa fa-download fa-lg&quot;]</value>
      <webElementGuid>d7b8f09a-00be-4497-85c4-1887acaf05bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[2]/button[2]/i</value>
      <webElementGuid>b2e8e1b3-5699-4b97-b192-f90e2261a0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>01acb586-476f-4410-8741-5c1946e34184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
