<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Previous_wizard</name>
   <tag></tag>
   <elementGuidId>4c6a145a-f09b-43bb-864c-1683864e6e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='wizard-esrx3kq-nav']/li/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-wizard-nav-previous</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d37fa447-455a-44b2-8de6-9d0ab5168574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous button. Click to go back to the previous tab</value>
      <webElementGuid>87606e4e-df9b-4b7d-a4b4-5f0a07c84800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>wizard-esrx3kq-previous</value>
      <webElementGuid>3077ed0d-dfca-43c0-b312-af6749e35958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-wizard-nav-previous</value>
      <webElementGuid>05261176-5157-4a70-b2a2-1ffc90c32a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>5705ab8d-04c3-445f-b407-11145c475509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-esrx3kq-nav&quot;)/li[1]/button[@class=&quot;btn btn-primary btn-wizard-nav-previous&quot;]</value>
      <webElementGuid>0a194ee3-c03b-4731-a2bf-82e4c8091028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='wizard-esrx3kq-nav']/li/button</value>
      <webElementGuid>2b8bd871-577b-4d6b-88ee-4047f1c0f156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', numeric only,'])[1]/following::button[1]</value>
      <webElementGuid>909a6a90-bd91-43ba-9eec-a963faae67ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='formsflow.ai'])[3]/preceding::button[1]</value>
      <webElementGuid>d69b792e-f11a-4d19-88ef-ff2bb3c1c9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Previous']/parent::*</value>
      <webElementGuid>aeaafa65-8bca-46e9-809a-3606cf1f0ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/button</value>
      <webElementGuid>c1da3c22-3876-4431-828e-fab7dcce66f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>1c1d62c1-0473-4fec-9f6c-377a03479f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
