<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__productfruits--container</name>
   <tag></tag>
   <elementGuidId>86c417f1-0a3b-4b0c-b094-ca9128700f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.productfruits--container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9139454e-65e4-4ea7-a488-34a256cbdcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productfruits--container</value>
      <webElementGuid>ded4ccc7-fbd7-4cf5-952f-df1d957eeff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-scroll&quot;]/div[@class=&quot;productfruits--container&quot;]</value>
      <webElementGuid>4efa984f-59f0-48c0-b877-60c61ef3918d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>28586c67-d109-4f52-9d6d-a7d7b2d3b143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
