<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter byApplication Name_text-filter-column-applicationName</name>
   <tag></tag>
   <elementGuidId>259fe106-0d93-4798-8f09-f70f3b2c542b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-column-applicationName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-column-applicationName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f7d796d-41ec-4f28-8b35-444ac6548de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delay</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>b589b141-10d5-4146-836d-d9c7ca78bc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c07a032-ee94-482f-b9a3-08f2bc7c0ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-column-applicationName</value>
      <webElementGuid>ebe638eb-5338-4956-9ddc-d99c847391bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter text-filter form-control icon-search</value>
      <webElementGuid>03adc927-6d1b-4809-8590-2bd5fc641fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Application Name</value>
      <webElementGuid>dd270acb-da2f-45d4-992e-116c415c2bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-column-applicationName&quot;)</value>
      <webElementGuid>927bdc76-6453-4873-a28a-c5a0a54a9aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-column-applicationName']</value>
      <webElementGuid>cdd0548e-ac31-4701-96b2-10b86813a04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/table/tbody/tr/th[2]/label/input</value>
      <webElementGuid>65568a15-1763-464f-b231-ffaa57b40281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/label/input</value>
      <webElementGuid>479580af-ebfd-40cb-bee4-1e4c83a5b8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-filter-column-applicationName' and @placeholder = ' Application Name']</value>
      <webElementGuid>f8b7b5ca-7d31-44c5-b7cc-e429b12ae0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
