<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_addwizardPage</name>
   <tag></tag>
   <elementGuidId>60a6d56f-fb96-42af-b194-9b453cd8da57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ol/li[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mr-2.badge.badge-success.wizard-page-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b969750-af94-4aba-aaf6-25f54f0a405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>addPage</value>
      <webElementGuid>66e4eda1-fd9e-4731-86b2-920df48ef5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 badge badge-success wizard-page-label</value>
      <webElementGuid>41e6cb70-73b0-4f1c-93c7-62dcb8e81fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create Page</value>
      <webElementGuid>312c1367-099a-4330-b716-c39af1288e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
           Page
        </value>
      <webElementGuid>f8eb73fa-f454-4884-a752-b5d1d660b78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;paper-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-baseline&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[2]/div[1]/div[1]/div[@class=&quot;p-4&quot;]/div[2]/div[1]/div[@class=&quot;formio builder row formbuilder&quot;]/div[@class=&quot;col-xs-8 col-sm-9 col-md-10 formarea&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[2]/span[@class=&quot;mr-2 badge badge-success wizard-page-label&quot;]</value>
      <webElementGuid>127833ad-4dc4-40ee-821e-4dfb8aa4d8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ol/li[2]/span</value>
      <webElementGuid>f778671f-350f-4e39-a301-87f02f082b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/following::span[1]</value>
      <webElementGuid>a382b170-afea-4120-b9b5-1ef721c539a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[2]/preceding::span[1]</value>
      <webElementGuid>b7d2b1e9-997d-4265-b077-4090ca477a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and Drop a form component'])[1]/preceding::span[2]</value>
      <webElementGuid>1f5cd832-f583-4814-bd2c-75f9854af8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Page']/parent::*</value>
      <webElementGuid>daf52f94-d7bd-4843-b544-965a600ec634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>d3406893-8d53-433c-9a93-dc4f706ebecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Create Page' and (text() = '
           Page
        ' or . = '
           Page
        ')]</value>
      <webElementGuid>a3f08af2-33fb-4976-9990-897fc553984d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
