<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Page 2_wizard</name>
   <tag></tag>
   <elementGuidId>2ec2f3cc-1d49-4b56-9b84-41d158532b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ol/li[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mr-2.badge.badge-info.wizard-page-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f84bd49e-fa13-4434-aabe-b9c9d7e71eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>gotoPage</value>
      <webElementGuid>baf5dd76-19ed-4787-9023-f75a908b37d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 badge badge-info wizard-page-label</value>
      <webElementGuid>37d4eaa8-c94f-4725-87ff-8976b4f811f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Page 2</value>
      <webElementGuid>e2256815-d618-428c-810c-a270b7c95490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page 2</value>
      <webElementGuid>aa17bb96-0aa5-424e-963b-b1ea8f978342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;paper-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-baseline&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[2]/div[1]/div[1]/div[@class=&quot;p-4&quot;]/div[2]/div[1]/div[@class=&quot;formio builder row formbuilder&quot;]/div[@class=&quot;col-xs-8 col-sm-9 col-md-10 formarea&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[2]/span[@class=&quot;mr-2 badge badge-info wizard-page-label&quot;]</value>
      <webElementGuid>a4a23bb8-537b-4c98-8865-671df06f1bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ol/li[2]/span</value>
      <webElementGuid>30b54e98-97db-4161-83f1-b8e6b5485f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/following::span[1]</value>
      <webElementGuid>7b36b7dd-4daa-4e9e-8e59-1e6a6575ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[2]/preceding::span[2]</value>
      <webElementGuid>5f4778ff-7d5d-4f0d-b5f1-90d0e3b595f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Page 2']/parent::*</value>
      <webElementGuid>21d24be0-5041-4441-a272-68ed4566945c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>2d155068-4a74-46ed-87ad-17052c77c5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Page 2' and (text() = 'Page 2' or . = 'Page 2')]</value>
      <webElementGuid>4211fe42-8ede-44fa-bcb3-42d2d42ff7b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
