<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Form</name>
   <tag></tag>
   <elementGuidId>9f4340de-ec28-4c8b-9205-3ed764e1a73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service-task-details-tab-form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'service-task-details-tab-form' and (text() = 'Form' or . = 'Form')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='service-task-details-tab-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25f50266-9c90-4c02-9c51-7250f7caead9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service-task-details-tab-form</value>
      <webElementGuid>cdeb7c7e-a63c-4983-be31-9d04d62efdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>348170bd-bf77-4acb-8718-f6bdd45314fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3a912d90-6dc8-45b8-ab0c-a03bf8915d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>078789ec-8b1c-4370-8835-823d5bb5d380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>service-task-details-tabpane-form</value>
      <webElementGuid>fbffd356-58aa-4e11-8cad-80625e87f212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c2de970-feb2-4ef2-9683-c3f05ae0dc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link active</value>
      <webElementGuid>6bb2cf2d-ac93-433e-b2e1-949a952afcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form</value>
      <webElementGuid>067c52cf-6e60-4bc2-ad3c-1946a2576521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service-task-details-tab-form&quot;)</value>
      <webElementGuid>54d6a309-df30-4c0b-8d98-3a6f2fc6b19c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='service-task-details-tab-form']</value>
      <webElementGuid>73443947-df20-4403-b660-323f90ec83e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div[2]/div/div/nav/a</value>
      <webElementGuid>2bfe3526-2ba0-495a-a3fa-9c0c96a15854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Form')])[2]</value>
      <webElementGuid>2b2551c3-2220-483b-a849-fda413adf349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='john.doe'])[1]/following::a[1]</value>
      <webElementGuid>d22621ee-8421-4326-a8bc-ff582086cd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='formsflow/formsflow-reviewer/clerk'])[1]/following::a[1]</value>
      <webElementGuid>a885da3f-520a-450c-9e41-2eec63789556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Business License Application'])[1]/preceding::a[3]</value>
      <webElementGuid>0cf2e8ed-26c1-4894-8a69-d62fdcacaa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW BUSINESS LICENCE APPLICATION'])[1]/preceding::a[3]</value>
      <webElementGuid>c7ff9686-16e2-436d-ab8b-37fc7e7c06b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form']/parent::*</value>
      <webElementGuid>ee80a41a-a33d-4e09-9b13-2d5ec3ed9a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>4045eb10-4a88-4e3d-9d8d-08f3fd50bc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>62684dfa-2af3-43f6-ab90-12420d7225e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'service-task-details-tab-form' and @href = '#' and (text() = 'Form' or . = 'Form')]</value>
      <webElementGuid>0a8a4b45-e5ef-4c3c-910a-542ffd1e817a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
