<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter byApplication Id</name>
   <tag></tag>
   <elementGuidId>cce3964a-b565-4ca8-94c4-ef52b7715042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-column-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-column-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90784e54-1e39-4f69-ab05-05d23d63165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delay</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>a3d41fe3-f340-436a-920a-ca70335832fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7128d20-3c5a-4491-b4f6-f79e5b8d04e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-column-id</value>
      <webElementGuid>2b45ccc0-b803-43e4-9c6a-a18e95edcf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter text-filter form-control icon-search</value>
      <webElementGuid>f1cc96c9-bd8e-4960-9f32-36eed31f05b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Application Id</value>
      <webElementGuid>3b576878-a6f5-4db2-896f-b9c506ccb258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-column-id&quot;)</value>
      <webElementGuid>e71ea2da-8f8c-414e-adba-542557f2d880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-column-id']</value>
      <webElementGuid>7a8fd47b-34a2-4024-b996-d0a652b031da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/table/tbody/tr/th/label/input</value>
      <webElementGuid>4a16616c-ed3d-41ff-9b95-8cabeb1e470c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b648cbad-e508-4ea0-9467-575501a42c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-filter-column-id' and @placeholder = ' Application Id']</value>
      <webElementGuid>9194b359-0b48-4507-a57e-10643264fc05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
