<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_form name</name>
   <tag></tag>
   <elementGuidId>fbb9ed75-d3bb-41d8-b1ec-0aa91dd376c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-filter-column-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @id = 'form1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-filter-column-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ce825ee-2b81-4464-8de1-31e9c5ddc7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delay</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>fb017125-5b28-4e98-b0e2-9e1e34959f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>42e97548-930d-458b-8d71-e070873c3c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form1</value>
      <webElementGuid>290bebec-4922-4624-a1a3-eb814134b291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter text-filter form-control icon-search</value>
      <webElementGuid>fb4391e8-3931-4ed9-8b7b-94288e9aec82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by form name</value>
      <webElementGuid>b77447f0-39ac-4ced-b682-23f77ed35a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-column-title&quot;)</value>
      <webElementGuid>a6131ecf-73e6-4d23-9220-7d687d36f38f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-column-title']</value>
      <webElementGuid>a87fa11e-0898-40ba-b1aa-12115718b27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/section/div/div/div/div/table/tbody/tr/th/label/input</value>
      <webElementGuid>f0ef4bc8-cf89-45d2-af53-2dfebd15d8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>76a6f3fb-0ba0-4106-96c2-bde3a851a145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-filter-column-title' and @placeholder = 'Search by form name']</value>
      <webElementGuid>319a3729-dd02-4897-abb7-6cd0dd4762ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
