<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_formsflowformsflow-reviewerclerk</name>
   <tag></tag>
   <elementGuidId>a9be0994-0962-4d6b-841e-3a1e2f74acfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div[2]/div/div/div[4]/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.group-align</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fb9d367-e865-461b-aed5-138425275f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group-align</value>
      <webElementGuid>f26901f9-4473-4d6a-a4d9-508ce947f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>formsflow/formsflow-reviewer/clerk</value>
      <webElementGuid>0f8cd1cd-bf91-44f8-b1a5-c2965b9d4081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;p-2 row&quot;]/div[@class=&quot;pl-0 col-xl-9 col-lg-9 col-md-8 col-sm-12 col-12&quot;]/div[@class=&quot;service-task-details&quot;]/div[@class=&quot;_loading_overlay_wrapper css-79elbk&quot;]/div[@class=&quot;actionable mb-4 row&quot;]/div[@class=&quot;center-position col-sm-4&quot;]/span[@class=&quot;group-align&quot;]</value>
      <webElementGuid>7cc0bdf6-4e88-4ff4-9d4b-f7c6147300bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div[2]/div/div/div[4]/div[3]/span</value>
      <webElementGuid>ca352aa3-affe-46b1-8994-6e5d36204f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim'])[1]/preceding::span[1]</value>
      <webElementGuid>3aa81ef2-78d5-493f-8bdb-2cf03fbf9ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='formsflow/formsflow-reviewer/clerk']/parent::*</value>
      <webElementGuid>8aa0e864-5edf-4c39-89f3-7e774f261df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/span</value>
      <webElementGuid>085f69b8-8c1c-48b6-93d9-7f63ad056136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'formsflow/formsflow-reviewer/clerk' or . = 'formsflow/formsflow-reviewer/clerk')]</value>
      <webElementGuid>75c13389-ce43-4b6a-ba88-bde622b3e11f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
