<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5118</name>
   <tag></tag>
   <elementGuidId>7ccc4c02-727c-41c7-8ae4-a0afff03be54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='application-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>62425117-dcf4-48c4-96d1-fde61da45856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>171aa5f5-2ff1-4500-bc09-329623347de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-id</value>
      <webElementGuid>5b84f63c-022e-47ad-a7f0-089447607cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5118</value>
      <webElementGuid>03141af9-727e-47a1-97c4-760315f49fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-id&quot;)</value>
      <webElementGuid>384a6438-56c3-4c52-8d71-9bb36731d5cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='application-id']</value>
      <webElementGuid>d1cb58d9-2924-4d5c-b89f-7b8b49745ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-details-tabpane-details']/div/div/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>2d0e26ac-d1f6-46ad-a4a5-2e4e016efb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::td[1]</value>
      <webElementGuid>2537ac11-c933-4429-98fb-3f3541f879d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Id'])[1]/following::td[2]</value>
      <webElementGuid>72c29715-c04e-4654-8d71-1cd69a8c0377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Name'])[1]/preceding::td[1]</value>
      <webElementGuid>61b9db53-e9ff-4a43-b98f-773eb227ab5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/preceding::td[2]</value>
      <webElementGuid>ba053bc9-ce89-4dc7-9747-6be3c845fb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5118']/parent::*</value>
      <webElementGuid>5027e287-b020-47b2-88d9-1ee23f81bc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>82cfdea9-b05c-486c-8733-4d2639a34dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'application-id' and (text() = '5118' or . = '5118')]</value>
      <webElementGuid>48f61942-0d7b-4b4b-9265-4cf0b6c3faa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
