<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Application Status</name>
   <tag></tag>
   <elementGuidId>bde71cc2-54f7-4ad8-89f6-b76d9db1fb03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='application-status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6c3b75dd-cf89-4034-817a-8a388a0ba63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>950a8eea-cd16-40a4-ae9d-676b795f954a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-status</value>
      <webElementGuid>62e56a6e-20e9-4a3d-b7a5-525c84ff80ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviewed</value>
      <webElementGuid>d80cc3f9-00d9-4c79-a7d5-374fa7b1c69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-status&quot;)</value>
      <webElementGuid>567984ae-1c99-4ad3-9c68-9024cbed5ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='application-status']</value>
      <webElementGuid>595d465d-3dc8-4cb5-87a8-913f0ca1bcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-details-tabpane-details']/div/div/div/div/table/tbody/tr[4]/td[3]</value>
      <webElementGuid>87451aa6-259a-45bf-91b6-56f5e8a4cbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[4]/following::td[1]</value>
      <webElementGuid>e4279e19-5711-426b-88c5-04382cdaf4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Status'])[1]/following::td[2]</value>
      <webElementGuid>ccbb18e7-8e2c-410c-b18c-b874eb70fd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submitted On'])[1]/preceding::td[1]</value>
      <webElementGuid>e4de0198-ec4b-4fa2-94a8-2cbdd01f0b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[5]/preceding::td[2]</value>
      <webElementGuid>c789774d-6dab-476c-a8e2-1ac81f13bb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviewed']/parent::*</value>
      <webElementGuid>508c4672-d004-4364-8162-4a4d956fdd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]</value>
      <webElementGuid>0dd1f5fb-88a7-4a6f-888c-19cbab55d5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'application-status' and (text() = 'Reviewed' or . = 'Reviewed')]</value>
      <webElementGuid>b545edaf-d839-439e-b42a-2fb861d0acc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
