<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_application number</name>
   <tag></tag>
   <elementGuidId>489e034c-667e-4722-b52a-dc44ee990a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='application-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ba4a36ae-0aaf-4c3e-9669-0c07c2392f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>40af64b6-ae70-46d7-bcc6-b7f829b56abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-id</value>
      <webElementGuid>aca7b5f5-6b8c-4805-bb46-ea2e5b24d87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5135</value>
      <webElementGuid>6645d620-157b-402b-acce-7429b9f064f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-id&quot;)</value>
      <webElementGuid>c9504c66-5353-4d68-9c35-36d78610f568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='application-id']</value>
      <webElementGuid>76b0be70-f8ba-4a2d-a9da-dfe669615dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-details-tabpane-details']/div/div/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>7610b842-2330-4619-b2e5-1fbbe554a10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::td[1]</value>
      <webElementGuid>ef5322fa-85b7-47c5-b8a5-b64d6aa13bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Id'])[1]/following::td[2]</value>
      <webElementGuid>1f9e5ca7-421c-4fe4-9ff5-05045396f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Name'])[1]/preceding::td[1]</value>
      <webElementGuid>2ee2bcf1-ca21-4ad0-ac2d-ada238918b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/preceding::td[2]</value>
      <webElementGuid>944f053f-bbf7-432a-aecd-f0a4c1cf2e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5135']/parent::*</value>
      <webElementGuid>75324aa8-3e1f-4f60-94fb-8cfae3893877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>d5654626-ee36-4879-b4f4-d59b22bca551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'application-id' and (text() = '5135' or . = '5135')]</value>
      <webElementGuid>afa6b3de-b365-4106-936d-b29b2a4bbf52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
