<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_processvariable</name>
   <tag></tag>
   <elementGuidId>c358593e-9f0a-4c76-abe6-9068333dc088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e45h9e-businessOperatingName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'filters position-box' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/div/div[1]/section/div/div[1]/div[1]/div[2]/div/div[2]/span[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>755abd6f-7dc1-436e-afd4-73097d861e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e45h9e-businessOperatingName</value>
      <webElementGuid>db7320e4-c4af-475a-b0cd-5e4e4376053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8970c91-a2dc-46fc-af7e-a038a52bd69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>a62d4be6-cf61-48d5-8bae-f33701fe128d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filters position-box</value>
      <webElementGuid>459eed57-9e8f-4e6e-a935-b96f26f0cd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bc6919c-b8d9-448f-a372-8c413d5ca41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[businessOperatingName]</value>
      <webElementGuid>b20bd1df-7852-4d88-9079-4b46ece11ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>389e4a09-f21c-4996-868b-0cf20a58d5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e45h9e-businessOperatingName&quot;)</value>
      <webElementGuid>5aadef8b-ba82-4df1-b343-3a969207d92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e45h9e-businessOperatingName']</value>
      <webElementGuid>59fe8e93-5269-4939-a0be-4f7448ae99be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e45h9e']/div/input</value>
      <webElementGuid>a211c873-bd11-4ce4-9cd8-3810377aea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>883cf748-4b9d-466c-979d-e688f33aaf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
