<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Proposed Business Start Date_fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>1de0e88f-7056-454e-8be6-8c09af839275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;e8pvw39&quot;)/div[1]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append&quot;]/span[@class=&quot;input-group-text&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e8pvw39']/div/div/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>78bdeabb-0301-42c9-be8c-0f0b2673a7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>a4ea1d5f-a857-4b43-9687-cdaac52704a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>73299317-fe83-4f59-83ed-a2a46213dc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e8pvw39&quot;)/div[1]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append&quot;]/span[@class=&quot;input-group-text&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>d67c853f-df6a-499f-b537-5cb90e47c427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e8pvw39']/div/div/div/span/i</value>
      <webElementGuid>442330c2-13b2-4f1f-ac0f-570af1272fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span/i</value>
      <webElementGuid>8ea838e6-0c72-4359-af1b-e417630032a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
