<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag and Drop a form component</name>
   <tag></tag>
   <elementGuidId>aa12cb8d-257a-4928-b6bb-c6e1753b2887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ek8xkbc']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.drag-and-drop-alert.alert.alert-info.no-drag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ddb8f343-70d4-4405-84bc-e46bb2cdfe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4da78958-24e5-418c-8cf3-4382eff988da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-noattach</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff6ff00f-1fe8-4422-848f-c4b497e037e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8dbca09d-2ac2-4dfa-801a-b352e4ec033b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-and-drop-alert alert alert-info no-drag</value>
      <webElementGuid>30a28e5b-f3a3-4538-9817-3dd30a80584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Drag and Drop a form component
</value>
      <webElementGuid>303ce766-f1b3-4630-b28a-9f5630e47961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ek8xkbc&quot;)/div[@class=&quot;formio-form&quot;]/div[@class=&quot;builder-components drag-container formio-builder-form&quot;]/div[@class=&quot;drag-and-drop-alert alert alert-info no-drag&quot;]</value>
      <webElementGuid>795e9dbc-f4da-45dd-bb70-2db10f7d47ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ek8xkbc']/div/div/div</value>
      <webElementGuid>032d2c92-15d8-4a8d-aac4-7e03cba6a60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[8]</value>
      <webElementGuid>0c063245-4e15-426a-8465-2c7eb4870328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drag and Drop a form component']/parent::*</value>
      <webElementGuid>576b36ef-8565-4b8e-b3c4-1c7f0f3a514a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>f44488e4-65cc-4bab-8b7c-8b90c1bc1ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
  Drag and Drop a form component
' or . = '
  Drag and Drop a form component
')]</value>
      <webElementGuid>0de2bcd3-03f7-4c14-8ace-08bc057a4be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
