<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text Field_datatextField</name>
   <tag></tag>
   <elementGuidId>c0751009-b63a-4b88-ac0e-5662b0e5a7dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e9g5uccm-textField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e9g5uccm-textField</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'e9g5uccm-textField' and @type = 'text' and @name = 'data[textField]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75440bef-75d3-40cc-ac6f-9cc2a3794c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0cfe771-804c-4fce-9664-5c049f2e56f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-e9g5uccm-textField</value>
      <webElementGuid>a6a8e149-aa7a-4b2f-a9f2-0b7657623678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e9g5uccm-textField</value>
      <webElementGuid>3ce0503b-d1b7-46c9-98d1-2e1b30d25281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc4d3bf6-0db3-49ef-a24a-62409516500e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>b515a457-6453-4e57-8725-c92a7d9fb64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8f9fc31-e56a-4dd9-a1dc-892e349edf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38d922e4-938d-41ab-b64f-5cab2694e79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[textField]</value>
      <webElementGuid>9b985e1c-6ad3-4d1b-896f-2f0dff6bbea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75bc395c-b0ee-4cbd-9b7e-10742b0e04ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c241f66c-ca1f-4102-a5ea-0fce06147971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e9g5uccm-textField&quot;)</value>
      <webElementGuid>c78f2611-66c1-4b8d-a05c-f9511f52c772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e9g5uccm-textField']</value>
      <webElementGuid>d5ad5fb8-d872-4e3a-8dc7-a8b9eaefd76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e9g5uccm']/div/input</value>
      <webElementGuid>4d1730ba-51c0-4e32-95df-4472c1111276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>69805a38-9acf-4b56-a592-37407d71f257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e9g5uccm-textField' and @type = 'text' and @name = 'data[textField]']</value>
      <webElementGuid>503e9ea3-cd57-4dad-b6f4-4dbb8f5b0e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
