<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>public_anonymous</name>
   <tag></tag>
   <elementGuidId>d9a9b2d0-d6eb-4eca-92cc-57b2cb6b3b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anonymous']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anonymous</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d9ca6ff-24a9-40bd-a0ea-abfa6fdf98a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0</value>
      <webElementGuid>cbd17f86-88aa-4693-9d42-d8d91307e836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>93f5eb53-5805-4b51-ab41-e912555bd625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>e959046e-c7eb-40b8-97f3-44eb6e579eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Check Anonymous</value>
      <webElementGuid>ec61fdd0-5a02-4701-9aaa-26573b2749bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonymous&quot;)</value>
      <webElementGuid>b7073e38-3da2-420c-a385-aecfe56cd305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anonymous']</value>
      <webElementGuid>24ae4c68-0967-4252-9f7a-e7e86379396b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-anonymous']/div/input</value>
      <webElementGuid>4fe892e6-6376-4517-8ce0-0a068d8f8ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>d79edbef-c49e-438c-93c7-426b6d74e97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'anonymous' and @title = 'Check Anonymous']</value>
      <webElementGuid>347528ff-891c-4d2b-a224-1c2b7cc85ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
