<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Form Saved</name>
   <tag></tag>
   <elementGuidId>f57d3593-f0ee-467e-9b5d-4a47de1f2719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@role = 'alert' and @class = 'Toastify__toast-body' and (text() = 'Form Saved.' or . = 'Form Saved.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ssmb56p5d']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>873ddf0c-8756-4406-8a46-3d2fed7b5623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>36ac69ec-3e9d-475f-9737-128fd62e70db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast-body</value>
      <webElementGuid>700c4146-1b2b-4f62-86a1-c15b764a0d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form Saved.</value>
      <webElementGuid>248ccab7-ce46-45b1-b78b-7a3f41d97982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssmb56p5d&quot;)/div[@class=&quot;Toastify__toast-body&quot;]</value>
      <webElementGuid>fc93f5aa-e862-49a0-b5ee-59e3db1a0823</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ssmb56p5d']/div</value>
      <webElementGuid>2fe8c7fe-740c-456c-8a12-bb3217864db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[1]/following::div[10]</value>
      <webElementGuid>72f0e7cf-0632-4cbb-a1ce-c170f34240ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[10]</value>
      <webElementGuid>1e675895-0cf5-40ed-b658-772cd63800a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design Form'])[1]/preceding::div[2]</value>
      <webElementGuid>c3173c97-6bb2-4eb9-aa68-0a54ed8bc765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate this form with a workflow?'])[1]/preceding::div[4]</value>
      <webElementGuid>8c7c6df6-291e-4653-b60a-b214594cf9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form Saved.']/parent::*</value>
      <webElementGuid>7eb19ee8-5db1-407e-bc8c-60b5597b3f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>64f809bc-588c-4b60-85b5-d82a73d3cb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Form Saved.' or . = 'Form Saved.')]</value>
      <webElementGuid>66f28865-a936-45b2-b33e-5989fa33c840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
