<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__productfruits--container</name>
   <tag></tag>
   <elementGuidId>13c61419-61e7-4015-bbea-17be8e4a3a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.productfruits--container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7214fc3c-003d-4124-a387-4b96c369f540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productfruits--container</value>
      <webElementGuid>000f23d0-3a19-495d-b696-4988b7405695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-scroll&quot;]/div[@class=&quot;productfruits--container&quot;]</value>
      <webElementGuid>fd0ae810-a990-43ea-ab56-d7ab40ed8ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>ceb38511-c524-4175-8138-6e63c1bc8fc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
