<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FormResource</name>
   <tag></tag>
   <elementGuidId>71f738dc-6101-44e6-b538-46c0fece7fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/section/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4013cabb-de46-401d-8406-e16e0b7e056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group</value>
      <webElementGuid>e119e5fe-2712-47f1-baf7-a5f760eff8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FormResource</value>
      <webElementGuid>11576d5c-4ddc-4d96-9d78-2eb9ab29f9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;custom-grid grid-forms&quot;]/div[@class=&quot;row mt-2 mx-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group&quot;]</value>
      <webElementGuid>289fe68e-1388-462c-b1f6-9d14432608e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/section/div/div/div</value>
      <webElementGuid>865c7d08-c163-4958-8b10-6faa36e5af69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[3]/preceding::div[2]</value>
      <webElementGuid>5d0c3330-123f-48f5-bddd-9be3387bf648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/preceding::div[2]</value>
      <webElementGuid>580e76fb-3c8e-433e-ab11-6ac237446b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>82a77b95-4d2a-404b-8d3d-ce55a21d116a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FormResource' or . = 'FormResource')]</value>
      <webElementGuid>833e2a31-4ffb-4ff0-b7d1-d8a41227505c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
