<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label_datalabel</name>
   <tag></tag>
   <elementGuidId>f7bf5f3c-f058-4352-8b02-1ae4fd7183c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e3prj76-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Field Label' and @class = 'form-control' and @type = 'text' and @name = 'data[label]' and @ref = 'input']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e3prj76-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2e9ecab-f18e-4487-9ba6-20fa3f9a3521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4948a5c-c4a3-4468-948a-9267222d0428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-e3prj76-label</value>
      <webElementGuid>ebdfd183-ff5a-4b8f-be52-e144886276d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3prj76-label</value>
      <webElementGuid>a0018334-469e-4448-ad1e-e52f5860b836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ab893ae-9ce2-440e-b69b-accde18b1889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Field Label</value>
      <webElementGuid>0b1b06a7-5695-412a-8d23-8c63534dbb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>476a7da2-873d-4a54-a5c3-2ec4e5781df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8ab0ac63-6833-441e-aa20-3c6a8b445b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9b3cd69-5847-4baa-8d9d-b85ec27af0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[label]</value>
      <webElementGuid>67775b7e-60cd-4afd-9325-f761fa6ea5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e8a7733-241c-446b-b9c8-dfdc8be6f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eada725d-4dcb-4349-9199-64fd80ba2547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3prj76-label&quot;)</value>
      <webElementGuid>bd84e3ae-e6fc-405f-b59e-db0e1e856ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3prj76-label']</value>
      <webElementGuid>cdd6e7be-0dbe-4486-a561-1cf1ba235838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3prj76']/div/input</value>
      <webElementGuid>8a34258a-c495-402a-a840-ac0fa77c6d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>eb73d586-5d63-44d3-ab6f-a1e8f4c2bd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3prj76-label' and @placeholder = 'Field Label' and @type = 'text' and @name = 'data[label]']</value>
      <webElementGuid>a1c15a6d-6cef-420f-9e84-30961b91afa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
