<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Applications  Automation Testing DemoDe_fc7834</name>
   <tag></tag>
   <elementGuidId>b51753d1-2598-424f-b142-c63ae69ff660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main > div.container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9db4f62-3a33-412d-9e62-710c8888fbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>c8d040b4-402b-47e6-9226-d97499dfe6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Applications / Automation Testing DemoDetailsFormHistoryProcess DiagramApplication Id:1596Application Name:Automation Testing DemoCreated By:john-smithApplication Status:CompletedSubmitted On:10/11/2022, 1:44:37 PMModified On:10/11/2022, 1:44:40 PM</value>
      <webElementGuid>368cc203-33af-4ccd-9029-5e9a0b2b3705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]</value>
      <webElementGuid>91608fe2-384b-4fa7-b74b-195b4e40b0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div</value>
      <webElementGuid>46dd7713-b266-4170-a47b-f95bfdce1aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[1]/following::div[9]</value>
      <webElementGuid>05ecb723-0334-4bea-963e-0048929058d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>45baad6a-7e25-4bb2-8256-d88145c8d3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Applications / Automation Testing DemoDetailsFormHistoryProcess DiagramApplication Id:1596Application Name:Automation Testing DemoCreated By:john-smithApplication Status:CompletedSubmitted On:10/11/2022, 1:44:37 PMModified On:10/11/2022, 1:44:40 PM' or . = '  Applications / Automation Testing DemoDetailsFormHistoryProcess DiagramApplication Id:1596Application Name:Automation Testing DemoCreated By:john-smithApplication Status:CompletedSubmitted On:10/11/2022, 1:44:37 PMModified On:10/11/2022, 1:44:40 PM')]</value>
      <webElementGuid>95d04653-d14a-445c-bed2-4dea8158e7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
