<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Download Form_fa fa-times</name>
   <tag></tag>
   <elementGuidId>f6967b9f-f91c-4e35-905b-c81dba8d1f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/section/div/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e3446284-3307-40f0-9f72-7a572fac2bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>999e0096-475c-4e26-844b-e87591d7467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;custom-grid grid-forms&quot;]/div[@class=&quot;row mt-2 mx-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn btn-outline-primary ml-2&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>abdb1adb-f041-4a14-bc4c-941055b7daeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/section/div/div/div/button/i</value>
      <webElementGuid>d75b43e0-4f8f-4979-9963-dd3c0c8d99f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/button/i</value>
      <webElementGuid>febcb674-0253-4742-80c5-a8fc37c130c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
