<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ViewEdit Form_fa fa-trash fa-lg delete_button_1</name>
   <tag></tag>
   <elementGuidId>22bb66a2-1dad-4211-9d2e-6c9f97808805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/section/div[2]/div/div/div/table/tbody/tr/td[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash.fa-lg.delete_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>56984ec3-a346-4731-8f7c-d1104eb9c2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash fa-lg delete_button</value>
      <webElementGuid>3d1cfc81-c8e2-4036-8847-097c95db1ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;custom-grid grid-forms&quot;]/div[2]/div[@class=&quot;_loading_overlay_wrapper css-79elbk&quot;]/div[@class=&quot;_loading_overlay_wrapper css-79elbk&quot;]/div[@class=&quot;react-bootstrap-table&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[1]/td[2]/span[1]/i[@class=&quot;fa fa-trash fa-lg delete_button&quot;]</value>
      <webElementGuid>5da2147d-aa27-4af1-9a1d-b17c00aa9c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/section/div[2]/div/div/div/table/tbody/tr/td[2]/span/i</value>
      <webElementGuid>766b0e5b-e72b-4d21-a064-98be5b3838f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/i</value>
      <webElementGuid>fc323cc0-ee88-42ae-9b2e-b9b3e1e92971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
