<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name of Public Body dropdown</name>
   <tag></tag>
   <elementGuidId>1d426510-5170-4dfc-8c73-4927e5a13d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-control.ui.fluid.selection.dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ezzg7kt9']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ezzg7kt9&quot;)/div[@class=&quot;field-wrapper&quot;]/div[@class=&quot;field-content&quot;]/div[@class=&quot;choices form-group formio-choices is-open is-flipped is-focused&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c63f3264-0c2d-4b45-a9ff-e5ea369dd800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui fluid selection dropdown</value>
      <webElementGuid>9cb7ce41-1652-481f-88d5-01f54b2fcb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1852fa4-5b80-4c35-a0a0-c2b8b9afa957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ezzg7kt9&quot;)/div[@class=&quot;field-wrapper&quot;]/div[@class=&quot;field-content&quot;]/div[@class=&quot;choices form-group formio-choices is-open is-flipped is-focused&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]</value>
      <webElementGuid>07a60ea9-f317-4b0b-b1bf-cd9e58613987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ezzg7kt9']/div/div[2]/div/div</value>
      <webElementGuid>fa8fc324-da29-45df-9523-676bcceb9db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Public Body To Which You Are Directing Your Request'])[1]/following::div[3]</value>
      <webElementGuid>9120c572-5af6-4ed5-b6ca-bec0e33eb80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/following::div[12]</value>
      <webElementGuid>f3266c27-a746-43bc-ba86-c7587b9cd776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Education, Skills &amp; Training'])[1]/preceding::div[2]</value>
      <webElementGuid>c908aaba-cd34-4654-97b5-87163d9ecdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agriculture'])[1]/preceding::div[3]</value>
      <webElementGuid>493ac919-55fa-4d0f-ad81-0aad9adb8688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>7783d855-b1c2-4632-a367-6d02fb649b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
