<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>28b98085-31a4-4ae7-b20d-f79cecee73fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-search-input > span.click-element</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'value' and @class = 'click-element' and (text() = '??' or . = '??')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@title = 'property' and @class = 'click-element' and (text() = '??' or . = '??')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8c4b3ee-99ff-4dee-868f-b9daa8e76250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>1999b420-902b-4f84-83bd-2bf7accd7b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-element</value>
      <webElementGuid>4f40a748-a230-4457-8e20-dd57cee58d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>??</value>
      <webElementGuid>5039d5cb-6bbe-4e5b-8a7c-b08f70f6d066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search-input&quot;)/span[@class=&quot;click-element&quot;]</value>
      <webElementGuid>8e4f4953-988a-4584-9e02-3721706228f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='task-search-input']/span</value>
      <webElementGuid>7ef5d917-e087-4410-9e1b-0d03015c9578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='applicationStatus'])[1]/following::span[4]</value>
      <webElementGuid>14e834ea-d0c6-41ee-a58d-2da653f02d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Variables :'])[1]/following::span[7]</value>
      <webElementGuid>ef095dfc-0e80-4cc7-b4ec-c52d8863ce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Variable, ignore case ofNamevalue'])[1]/preceding::span[2]</value>
      <webElementGuid>d6faa93b-099b-4044-a9e5-44dbafd9a01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Applications'])[1]/preceding::span[9]</value>
      <webElementGuid>fab6b230-1f17-492b-83ea-7c482616f680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='??']/parent::*</value>
      <webElementGuid>2969fbd7-6e4f-477c-90f8-7a9852697981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span[2]/span</value>
      <webElementGuid>8b313e0a-9f96-4600-98b5-d7443322e857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'value' and (text() = '??' or . = '??')]</value>
      <webElementGuid>55b3c993-0693-4b56-994b-bab9e60d22e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
