<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Path_anonymous</name>
   <tag></tag>
   <elementGuidId>8f7da37f-e73f-412a-9df0-19876fb047b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anonymous']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anonymous</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f8f31d3-a5d0-4ed8-a82e-c10186e43df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0</value>
      <webElementGuid>9c819994-5b73-4f4c-b8b1-1f58c816015d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>860b335c-099b-4e8f-90a3-081da47b17a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>48cd0c99-1b25-4c41-a164-2369be0e4882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Make this form public</value>
      <webElementGuid>424d1bdc-506a-41c1-9d30-8283962a49f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>86689290-3554-41e3-92c8-fd18f92c144c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonymous&quot;)</value>
      <webElementGuid>1b406516-b0cd-4299-bb1f-29aa8bfbba16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anonymous']</value>
      <webElementGuid>f5f06fec-972f-43dc-a8ac-8bccdc758424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-anonymous']/div/input</value>
      <webElementGuid>aea1876e-f669-4cc9-b9b8-e45d83c5d4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>c866e338-9051-4986-86a6-d0e0910409b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'anonymous' and @title = 'Make this form public']</value>
      <webElementGuid>d3812cf6-45c2-48ef-ac3a-1feed79abccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
